# Generated by Django 5.0.3 on 2024-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
